"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg:#061626 fg:#050e18)\
$directory\
[](fg:#061626 bg:#0e2a47)\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
[](fg:#0e2a47 bg:#24274d)\
$nodejs\
$rust\
$golang\
$php\
$terraform\
[](fg:#24274d)\
$time\
$cmd_duration\
$aws\
$battery\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#061626"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#0e2a47"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#0e2a47)]($style)'

[git_status]
style = "bg:#0e2a47"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#0e2a47)]($style)'

[nodejs]
symbol = ""
style = "bg:#24274d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#24274d)]($style)'

[rust]
symbol = ""
style = "bg:#24274d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#24274d)]($style)'

[golang]
symbol = ""
style = "bg:#24274d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#24274d)]($style)'

[php]
symbol = ""
style = "bg:#24274d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#24274d)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb)]($style)'

[kubernetes]
disabled = false

[terraform]
format = 'via [$symbol$version $workspace]($style) '

[[battery.display]]
threshold = 30
