name: actions-lints

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actions-lints:
    name: actionlint
    permissions:
      contents: read
    uses: yaizuuuu/shared-workflows/.github/workflows/actions-lints.yml@dea1147981b5158dd5642b7cf9b4c78b4f91fea0 # v0.0.2
