name: secret-scan

on:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install git-secrets
        # Pin to git-secrets 1.2.1 (3f1138c1aa28a5772f931ea2908ad05d07b7f313)
        run: |
          git init /tmp/git-secrets
          git -C /tmp/git-secrets remote add origin https://github.com/awslabs/git-secrets.git
          git -C /tmp/git-secrets fetch --depth 1 origin 3f1138c1aa28a5772f931ea2908ad05d07b7f313
          git -C /tmp/git-secrets checkout --detach FETCH_HEAD
          sudo make -C /tmp/git-secrets install
      - name: Scan
        run: |
          git secrets --register-aws
          git secrets --scan-history
